# Generated by Django 2.2.3 on 2019-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditingView',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('doj', models.DateField(auto_now=True)),
            ],
        ),
    ]
